[package]
name = "entry"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "程序的入口"

[dependencies]
bevy = { version = "0.17.3" }
utils = { path = "../utils" }

[dev-dependencies]
rstest = { workspace = true }
