[package]
name = "embedded_assets"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "把assets嵌入到程序中"

[dependencies]
bevy = { version = "0.17.3" }
