name: CI

on:
  push:
    branches:
      - main
    # 忽略所有 tag push
    tags-ignore:
      - "*"

env:
  # 用来控制终端输出是否使用颜色
  CARGO_TERM_COLOR: never
  RUST_BACKTRACE: "full"
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  procedures:
    name: Procedures
    runs-on: windows-latest
    if: github.ref_type == 'branch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: windows-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: windows-cargo-registry-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: windows-cargo-build-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          restore-keys: windows-cargo-build-

      - name: Check workspace compilation
        run: cargo check --workspace

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features

      - name: Test
        run: cargo test --workspace --verbose
